//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Wenn der Code neu generiert wird, gehen alle Änderungen an dieser Datei verloren
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

/// <summary>
/// Gamelogic und Inputhandling
/// </summary>
public class Actions
{
	public virtual void attack(Interactive attacker, Interactive attacked)
	{
		throw new System.NotImplementedException();
	}

	public virtual void consume(Player player, Consumable consumable)
	{
		throw new System.NotImplementedException();
	}

}

