//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Wenn der Code neu generiert wird, gehen alle Änderungen an dieser Datei verloren
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Armor : Item
{
	private float bleedResist
	{
		get;
		set;
	}

	private float damageResist
	{
		get;
		set;
	}

	private int durability
	{
		get;
		set;
	}

	private int actionPointModifier
	{
		get;
		set;
	}

}

