//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Wenn der Code neu generiert wird, gehen alle Änderungen an dieser Datei verloren
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class GameWorld
{
	private static Vector2 worldSize
	{
		get;
		set;
	}

	private Player player1
	{
		get;
		set;
	}

	private Player player2
	{
		get;
		set;
	}

	private Player player3
	{
		get;
		set;
	}

	private Player player4
	{
		get;
		set;
	}

	private Array<Enemy> enemies
	{
		get;
		set;
	}

	private Array<Item> items
	{
		get;
		set;
	}

	private GameStates GameState
	{
		get;
		set;
	}

}

