//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Wenn der Code neu generiert wird, gehen alle Änderungen an dieser Datei verloren
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Interactive : GameEntity
{
	protected virtual int healthPoints
	{
		get;
		set;
	}

	protected virtual int actionPoints
	{
		get;
		set;
	}

	protected virtual int sightRadius
	{
		get;
		set;
	}

	public virtual void setHealthPoints(int hp)
	{
		throw new System.NotImplementedException();
	}

	public virtual void setActionPoints(int ap)
	{
		throw new System.NotImplementedException();
	}

	public virtual int getHealthPoints()
	{
		throw new System.NotImplementedException();
	}

	public virtual int getActionPoints()
	{
		throw new System.NotImplementedException();
	}

}

