//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Wenn der Code neu generiert wird, gehen alle Änderungen an dieser Datei verloren
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Player : Interactive
{
	private Item item1
	{
		get;
		set;
	}

	private Item item2
	{
		get;
		set;
	}

	private Weapon activeWeapon
	{
		get;
		set;
	}

	private Item item3
	{
		get;
		set;
	}

	private Item item4
	{
		get;
		set;
	}

	public Player(string type)
	{
	}

}

