//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Wenn der Code neu generiert wird, gehen alle Änderungen an dieser Datei verloren
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Weapon : Pickup, Item
{
	private int damageModifier
	{
		get;
		set;
	}

	private float hitChance
	{
		get;
		set;
	}

	private float bleedChance
	{
		get;
		set;
	}

	private float criticalChance
	{
		get;
		set;
	}

	private float criticalModifier
	{
		get;
		set;
	}

	private int actionPointModifier
	{
		get;
		set;
	}

}

